[theme]
primaryColor = "#1b466b"        # Your blue
backgroundColor = "#f0f2f6"     # Light grey background
secondaryBackgroundColor = "#d9d9d9"  # Another grey for sidebars, etc
textColor = "#262730"           # Dark text
font = "sans serif"             # or "serif", "monospace"